pipeline {
  agent any
  stages {
    stage('Test') {
      steps {
        withMaven {
            sh 'mvn -f projectOne/pom.xml test'
        }
      }
    }
    
    stage('Build') {
          when {
             branch 'main'
          }
          steps {
            withMaven {

              sh 'mvn -f projectOne/pom.xml clean install'
              sh 'mvn -f projectOne/pom.xml clean package -DskipTests'

            }
          }
    }
  
  }
}
