pipeline {
  environment {
        registry = 'olvmky/reimb-api'
        dockerHubCreds = 'docker_hub'
        dockerImage = ''
  }
  
  agent any
  stages {
    stage('Test') {
      steps {
        withMaven {
            sh 'mvn -f projectOne/pom.xml test'
        }
      }
    }
    
    stage('Build') {
          when {
             branch 'main'
          }
          steps {
            withMaven {

              sh 'mvn -f projectOne/pom.xml clean install'
              sh 'mvn -f projectOne/pom.xml clean package -DskipTests'

            }
          }
    }
    
    stage('Docker Build') {
           when {
               branch 'main'
           }
           steps {
             dir('projectOne/') {
               script {
                  echo "$registry:$currentBuild.number"
                  dockerImage = docker.build "$registry"
               }
             }
           }
       }
  
  }
}
