pipeline {
  environment {
        registry = 'olvmky/reimb-api'
        dockerHubCreds = 'docker_hub'
        dockerImage = ''
        deploymentFile = 'projectOne/k8s/deployment.yml'
  }
  
  agent any
  stages {
    stage('Test') {
      steps {
        withMaven {
            sh 'mvn -f projectOne/pom.xml test'
        }
      }
    }
    
    stage('Build') {
          when {
             branch 'main'
          }
          steps {
            withMaven {
              sh 'mvn -f projectOne/pom.xml clean install'
              sh 'mvn -f projectOne/pom.xml clean package -DskipTests'
            }
          }
    }
    
    stage('Docker Build') {
           when {
               branch 'main'
           }
           steps {
               script {
                  echo "$registry:$currentBuild.number"
                  dockerImage = docker.build ("$registry", "-f projectOne/Dockerfile .")
               }
           }
       }

    stage('Docker Deliver') {
      when {
        branch 'main'
      }
      steps {
        script {
          docker.withRegistry('',dockerHubCreds) {
                    dockerImage.push()
          }
        }
      }
    }

//     stage('Scan') {
//       steps {
//         withSonarQubeEnv(installationName: 'sq1') {
//           sh './mvnw clean org.sonarsource.scanner.maven:sonar-maven-plugin:3.9.0.2155:sonar'
//         }
//       }
//     }

    stage('Deploy to GKE') {
            when {
                branch 'main'
            }
            steps{
               sh 'sed -i "s/%TAG%/$BUILD_NUMBER/g" ./projectOne/k8s/deployment.yml'
               sh 'cat ./projectOne/k8s/deployment.yml'
               step([$class: 'KubernetesEngineBuilder',
                    projectId: 'active-road-343813',
                    clusterName: 'active-road-343813-gke',
                    zone: 'us-central1',
                    manifestPattern: 'projectOne/k8s/',
                    credentialsId: 'active-road-343813',
                    verifyDeployments: true
               ])

               cleanWs()

               discordSend description: "Build #$currentBuild.number",
                    link: BUILD_URL, result: currentBuild.currentResult,
                    title: JOB_NAME,
                    webhookURL: "https://discord.com/api/webhooks/946097550514061343/7IRGxvAsw24cbGPIHXE15gtxCvzQQtRl3e5DEcm7arQpC6x3cVJPXXWZo7UWHKyJumuW"
            }
    }

  }
}
