server:
  port: 8088

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: emailapi302@gmail.com
    password: revature123
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        smpt:
          debug: true

